# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BINGX_AUTO.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5 import QtWidgets
from PyQt5.QtCore import QThread, pyqtSignal

class Ui_BACKGROUND(object):
    def setupUi(self, BACKGROUND):
        BACKGROUND.setObjectName("BACKGROUND")
        BACKGROUND.resize(756, 714)
        BACKGROUND.setLayoutDirection(QtCore.Qt.LeftToRight)
        BACKGROUND.setStyleSheet("background-color: rgb(0, 20, 40);")
        self.Choose_coin = QtWidgets.QComboBox(BACKGROUND)
        self.Choose_coin.setGeometry(QtCore.QRect(20, 70, 131, 31))
        self.Choose_coin.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.Choose_coin.setObjectName("Choose_coin")
        self.label = QtWidgets.QLabel(BACKGROUND)
        self.label.setGeometry(QtCore.QRect(20, 120, 251, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background: transparent;  /* 设置背景透明 */\n"
"    color: rgb(102, 153, 204);\n"
"}")
        self.label.setObjectName("label")
        self.NOW_PRICE = QtWidgets.QLabel(BACKGROUND)
        self.NOW_PRICE.setGeometry(QtCore.QRect(260, 120, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        self.NOW_PRICE.setFont(font)
        self.NOW_PRICE.setStyleSheet("QLabel {\n"
"    background: transparent;  /* 设置背景透明 */\n"
"    color: rgb(102, 153, 204);\n"
"}")
        self.NOW_PRICE.setObjectName("NOW_PRICE")
        self.label_2 = QtWidgets.QLabel(BACKGROUND)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 251, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background: transparent;  /* 设置背景透明 */\n"
"   color: rgb(102, 153, 204);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(BACKGROUND)
        self.label_3.setGeometry(QtCore.QRect(20, 300, 251, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    background: transparent;  /* 设置背景透明 */\n"
"   color: rgb(102, 153, 204);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(BACKGROUND)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 251, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    background: transparent;  /* 设置背景透明 */\n"
"    color: rgb(102, 153, 204);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.O_Asset = QtWidgets.QLabel(BACKGROUND)
        self.O_Asset.setGeometry(QtCore.QRect(260, 180, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(22)
        self.O_Asset.setFont(font)
        self.O_Asset.setStyleSheet("QLabel {\n"
"    background: transparent;  /* 设置背景透明 */\n"
"    color: rgb(102, 153, 204);\n"
"}")
        self.O_Asset.setObjectName("O_Asset")
        self.ASSET = QtWidgets.QLabel(BACKGROUND)
        self.ASSET.setGeometry(QtCore.QRect(260, 240, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(22)
        self.ASSET.setFont(font)
        self.ASSET.setStyleSheet("QLabel {\n"
"    background: transparent;  /* 设置背景透明 */\n"
"   color: rgb(102, 153, 204);\n"
"}")
        self.ASSET.setObjectName("ASSET")
        self.HOLD = QtWidgets.QLabel(BACKGROUND)
        self.HOLD.setGeometry(QtCore.QRect(260, 300, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(22)
        self.HOLD.setFont(font)
        self.HOLD.setStyleSheet("QLabel {\n"
"    background: transparent;  /* 设置背景透明 */\n"
"   color: rgb(102, 153, 204);\n"
"}")
        self.HOLD.setObjectName("HOLD")
        self.label_5 = QtWidgets.QLabel(BACKGROUND)
        self.label_5.setGeometry(QtCore.QRect(640, 20, 101, 91))
        self.label_5.setText("")
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setPixmap(QtGui.QPixmap("FEC15FF3-E050-48D9-9D9C-96211AD8B989.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(BACKGROUND)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 601, 31))
        self.label_6.setStyleSheet("QLabel {\n"
"    font: 16pt \"Arial\";\n"
"    background-color: rgb(218, 218, 218);  /* 设置背景颜色 */\n"
"    border: 1px solid #707070;  /* 设置边框颜色 */\n"
"    border-radius: 5px;  /* 设置边框圆角半径 */\n"
"    padding: 5px;  /* 设置内边距 */\n"
"}")
        self.label_6.setObjectName("label_6")
        self.USE_INFO = QtWidgets.QPushButton(BACKGROUND)
        self.USE_INFO.setGeometry(QtCore.QRect(500, 70, 121, 31))
        self.USE_INFO.setStyleSheet("QPushButton {\n"
"    background-color: rgb(218, 218, 218);  /* 設置背景顏色 */\n"
"    border: 1px solid #707070;  /* 設置邊框顏色 */\n"
"    border-radius: 5px;  /* 設置邊框圓角半徑 */\n"
"    padding: 5px;  /* 設置內邊距 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(238, 238, 238);  /* 鼠標懸停時的背景顏色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);  /* 按下時的背景顏色 */\n"
"}\n"
"")
        self.USE_INFO.setObjectName("USE_INFO")
        self.RUN = QtWidgets.QPushButton(BACKGROUND)
        self.RUN.setGeometry(QtCore.QRect(180, 70, 131, 31))
        self.RUN.setStyleSheet("QPushButton {\n"
"    background-color: rgb(218, 218, 218);  /* 設置背景顏色 */\n"
"    border: 1px solid #707070;  /* 設置邊框顏色 */\n"
"    border-radius: 5px;  /* 設置邊框圓角半徑 */\n"
"    padding: 5px;  /* 設置內邊距 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(238, 238, 238);  /* 鼠標懸停時的背景顏色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);  /* 按下時的背景顏色 */\n"
"}\n"
"")
        self.RUN.setObjectName("RUN")
        self.STOP = QtWidgets.QPushButton(BACKGROUND)
        self.STOP.setGeometry(QtCore.QRect(340, 70, 131, 31))
        self.STOP.setStyleSheet("QPushButton {\n"
"    background-color: rgb(218, 218, 218);  /* 設置背景顏色 */\n"
"    border: 1px solid #707070;  /* 設置邊框顏色 */\n"
"    border-radius: 5px;  /* 設置邊框圓角半徑 */\n"
"    padding: 5px;  /* 設置內邊距 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(238, 238, 238);  /* 鼠標懸停時的背景顏色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);  /* 按下時的背景顏色 */\n"
"}\n"
"")
        self.STOP.setObjectName("STOP")
        self.SHOW = QtWidgets.QTextEdit(BACKGROUND)
        self.SHOW.setGeometry(QtCore.QRect(20, 360, 611, 331))
        self.SHOW.setStyleSheet("font: 12pt \"新細明體\";\n"
"color: rgb(255, 255, 255);")
        self.SHOW.setObjectName("SHOW")

        self.retranslateUi(BACKGROUND)
        QtCore.QMetaObject.connectSlotsByName(BACKGROUND)

    def retranslateUi(self, BACKGROUND):
        _translate = QtCore.QCoreApplication.translate
        BACKGROUND.setWindowTitle(_translate("BACKGROUND", "BINGX_AUTO"))
        self.label.setText(_translate("BACKGROUND", "現在價位    ："))
        self.NOW_PRICE.setText(_translate("BACKGROUND", "NOW_PRICE"))
        self.label_2.setText(_translate("BACKGROUND", "期初資金    ："))
        self.label_3.setText(_translate("BACKGROUND", "當前持倉    ："))
        self.label_4.setText(_translate("BACKGROUND", "當前資金    ："))
        self.O_Asset.setText(_translate("BACKGROUND", "O_Asset"))
        self.ASSET.setText(_translate("BACKGROUND", "ASSET"))
        self.HOLD.setText(_translate("BACKGROUND", "HOLD"))
        self.label_6.setText(_translate("BACKGROUND", "NOW_TIME"))
        self.USE_INFO.setText(_translate("BACKGROUND", "USE_INFO"))
        self.RUN.setText(_translate("BACKGROUND", "RUN"))
        self.STOP.setText(_translate("BACKGROUND", "STOP"))


class MainApp(QtWidgets.QMainWindow, Ui_BACKGROUND):
    def __init__(self):
        super().__init__()
        self.setupUi(self)  # 初始化UI

def main():
    app = QtWidgets.QApplication(sys.argv)  # 創建應用程序實例
    main_window = MainApp()  # 創建主窗口實例
    main_window.show()  # 顯示窗口
        
    BACKGROUND = QtWidgets.QDialog()
    ui = Ui_BACKGROUND()
    ui.setupUi(BACKGROUND)

    sys.exit(app.exec_())  # 開始應用程序的事件循環

if __name__ == '__main__':
    main()